---
- name: Download files and run shell script
  hosts: all

  tasks:
  - name: 1、检查运维作业工作目录，没有则创建
    file:
      path: "{{ workdir }}"
      state: directory

  - name: 2、工作目录加入写权限
    file:
      path: "{{ workdir }}"
      mode: '0777'
    when: not ansible_check_mode

  - name: 3、下载指定软件(默认覆盖本地同名文件)
    get_url:
      url: "{{ item.value }}"
      dest: "{{ workdir }}/{{ item.key }}"
      mode: '0777'
      force: yes
    with_dict:
      "{{ fileList }}"
    when: not ansible_check_mode

  - name: 4、创建临时脚本文件
    shell: "echo \"{{ shell }}\" > /{{ workdir }}/temp.sh"

  - name: 5、临时脚本文件添加执行权限
    shell: "chmod +x {{ workdir }}/temp.sh"

  - name: 6、执行临时脚本文件
    shell: "{{ workdir }}/temp.sh > {{ workdir }}/temp.log"

  - name: 查看输出
    shell: "cat {{ workdir }}/temp.log"
    register: output
    
  - name: 查看输出
    debug:
      var: output.stdout_lines
      
  - name: 清理临时脚本文件
    file:
      path: "{{ workdir }}/temp.sh"
      state: absent
