---
- name: Download files and run shell script
  hosts: all

  tasks:
  - name: 1、检查运维作业工作目录，没有则创建
    file:
      path: "{{ workdir }}"
      state: directory

  - name: 2、工作目录加入写权限
    file:
      path: "{{ workdir }}"
      mode: '0777'
    when: not ansible_check_mode

  - name: 3、下载指定软件(默认覆盖本地同名文件)
    get_url:
      url: "{{ item.value }}"
      dest: "{{ workdir }}/{{ item.key }}"
      mode: '0777'
      force: yes
    with_dict:
      "{{ fileList }}"
    when: not ansible_check_mode

  - name: 4、创建临时脚本文件
    shell: "mkdir -p {{ workdir }}/steamer_temp_ops_sh_file && echo \"{{ shell }}\" > /{{ workdir }}/steamer_temp_ops_sh_file/temp_history_id_{{ ops_history_id }}.sh"

  - name: 5、临时脚本文件添加执行权限
    shell: "chmod +x {{ workdir }}/steamer_temp_ops_sh_file/temp_history_id_{{ ops_history_id }}.sh"

  - name: 6、执行临时脚本文件
    shell: "mkdir -p {{ workdir }}/steamer_temp_ops_log_file && {{ workdir }}/steamer_temp_ops_sh_file/temp_history_id_{{ ops_history_id }}.sh > {{ workdir }}/steamer_temp_ops_log_file/temp_history_id_{{ ops_history_id }}.log"

  - name: 7、查看执行输出
    shell: "cat {{ workdir }}/steamer_temp_ops_log_file/temp_history_id_{{ ops_history_id }}.log"    
